version: 0.2

phases:
  build:
    commands:
      # prepare the release (update versions, changelog etc.)
      - git-release --prepare

      # run linters
      - tox -e flake8,twine

      # run unit tests
      - AWS_ACCESS_KEY_ID= AWS_SECRET_ACCESS_KEY= AWS_SESSION_TOKEN=
        AWS_CONTAINER_CREDENTIALS_RELATIVE_URI= AWS_DEFAULT_REGION=
        tox -e py37,py38,py39 --parallel all -- test/unit

      # publish the release to github
      - git-release --publish

artifacts:
  files:
    - dist/sagemaker_tensorflow_training-*.tar.gz
  name: ARTIFACT_1
  discard-paths: yes
