version: 0.2

env:
  variables:
    FRAMEWORK_VERSION: '2.7.1'
    CPU_INSTANCE_TYPE: 'ml.c4.xlarge'
    ECR_REPO: 'sagemaker-test'

phases:
  pre_build:
    commands:
      - start-dockerd
      - ACCOUNT=$(aws --region $AWS_DEFAULT_REGION sts --endpoint-url https://sts.$AWS_DEFAULT_REGION.amazonaws.com get-caller-identity --query 'Account' --output text)
      - PR_NUM=$(echo $CODEBUILD_SOURCE_VERSION | grep -o '[0-9]\+')
      - BUILD_ID="$(echo $CODEBUILD_BUILD_ID | sed -e 's/:/-/g')"
      - echo 'Pull request number:' $PR_NUM '. No value means this build is not from a pull request.'

  build:
    commands:
      # no-op tests to prioritize dlc tests
      - TOX_PARALLEL_NO_SPINNER=1
      - PY_COLORS=0