version: 0.2

phases:
  build:
    commands:
      - TOX_PARALLEL_NO_SPINNER=1
      - PY_COLORS=0

      # run linters
      - tox -e flake8,twine

      # run unit tests
      - tox -e py37 --parallel all test/unit
