version: 0.2

env:
  variables:
    FRAMEWORK_VERSION: '1.15.2'
    ECR_REPO: 'sagemaker-test'
    GITHUB_REPO: 'sagemaker-tensorflow-container'
    SETUP_FILE: 'setup_cmds.sh'
    SETUP_CMDS: '#!/bin/bash\npip install --upgrade pip\npip install -U -e .\npip install -U -e .[test]'
    CPU_DOCKERFILE: 'Dockerfile.cpu'
    GPU_DOCKERFILE: 'Dockerfile.gpu'

phases:
  pre_build:
    commands:
      - start-dockerd
      - ACCOUNT=$(aws --region $AWS_DEFAULT_REGION sts --endpoint-url https://sts.$AWS_DEFAULT_REGION.amazonaws.com get-caller-identity --query 'Account' --output text)
      - PREPROD_IMAGE="$ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO"
      - PROD_IMAGE="763104351884.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/tensorflow-training"
      - PR_NUM=$(echo $CODEBUILD_SOURCE_VERSION | grep -o '[0-9]\+')
      - echo 'Pull request number:' $PR_NUM '. No value means this build is not from pull request.'

  build:
    commands:
      # install
      - pip3 install -U -e .[test]

      # run flake8
      - tox -e flake8,twine

      - root_dir=$(pwd)
      - build_id="$(echo $CODEBUILD_BUILD_ID | sed -e 's/:/-/g')"

      # Find build artifacts
      - build_artifacts=$root_dir/docker/build_artifacts

      # login so we can pull prod images for cache
      - $(aws ecr get-login --registry-ids 763104351884 --no-include-email --region $AWS_DEFAULT_REGION)

      # build py2 images

      # prepare build context
      - build_dir="$root_dir/docker/$FRAMEWORK_VERSION/py2"
      - cp $build_artifacts/*.py $build_dir/
      - cd $build_dir

      # build cpu image
      - prod_tag="$FRAMEWORK_VERSION-cpu-py2"
      - CPU_TAG_PY2="$prod_tag-$build_id"
      - docker pull $PROD_IMAGE:$prod_tag
      - build_cmd="docker build --cache-from $PROD_IMAGE:$prod_tag -f $CPU_DOCKERFILE -t $PREPROD_IMAGE:$CPU_TAG_PY2 . "
      - execute-command-if-has-matching-changes "$build_cmd" "test/" "docker/*" "buildspec.yml"

      # build gpu image
      - prod_tag="$FRAMEWORK_VERSION-gpu-py2"
      - GPU_TAG_PY2="$prod_tag-$build_id"
      - docker pull $PROD_IMAGE:$prod_tag
      - build_cmd="docker build --cache-from $PROD_IMAGE:$prod_tag -f $GPU_DOCKERFILE -t $PREPROD_IMAGE:$GPU_TAG_PY2 . "
      - execute-command-if-has-matching-changes "$build_cmd" "test/" "docker/*" "buildspec.yml"

      # build py3 images

      # prepare build context
      - build_dir="$root_dir/docker/$FRAMEWORK_VERSION/py3"
      - cp $build_artifacts/*.py $build_dir/
      - cd $build_dir

      # build cpu image
      - prod_tag="$FRAMEWORK_VERSION-cpu-py3"
      - CPU_TAG_PY3="$prod_tag-$build_id"
      - docker pull $PROD_IMAGE:$prod_tag
      - build_cmd="docker build --cache-from $PROD_IMAGE:$prod_tag -f $CPU_DOCKERFILE -t $PREPROD_IMAGE:$CPU_TAG_PY3 . "
      - execute-command-if-has-matching-changes "$build_cmd" "test/" "docker/*" "buildspec.yml"

      # build gpu image
      - prod_tag="$FRAMEWORK_VERSION-gpu-py3"
      - GPU_TAG_PY3="$prod_tag-$build_id"
      - docker pull $PROD_IMAGE:$prod_tag
      - build_cmd="docker build --cache-from $PROD_IMAGE:$prod_tag -f $GPU_DOCKERFILE -t $PREPROD_IMAGE:$GPU_TAG_PY3 . "
      - execute-command-if-has-matching-changes "$build_cmd" "test/" "docker/*" "buildspec.yml"

      # push images to ecr
      - $(aws ecr get-login --registry-ids $ACCOUNT --no-include-email --region $AWS_DEFAULT_REGION)
      - docker push $PREPROD_IMAGE:$CPU_TAG_PY2
      - execute-command-if-has-matching-changes "$push_cmd" "test/" "docker/*" "buildspec.yml"
      - docker push $PREPROD_IMAGE:$GPU_TAG_PY2
      - execute-command-if-has-matching-changes "$push_cmd" "test/" "docker/*" "buildspec.yml"
      - docker push $PREPROD_IMAGE:$CPU_TAG_PY3
      - execute-command-if-has-matching-changes "$push_cmd" "test/" "docker/*" "buildspec.yml"
      - docker push $PREPROD_IMAGE:$GPU_TAG_PY3
      - execute-command-if-has-matching-changes "$push_cmd" "test/" "docker/*" "buildspec.yml"

      # launch remote gpu instance
      - instance_type='p2.xlarge'
      - create-key-pair
      - launch-ec2-instance --instance-type $instance_type --ami-name dlami-ubuntu

      # run cpu integration tests
      - py3_cmd="IGNORE_COVERAGE=- tox -e py36 -- test/integration/local --region $AWS_DEFAULT_REGION --docker-base-name $PREPROD_IMAGE --tag $CPU_TAG_PY3 --framework-version $FRAMEWORK_VERSION --py-version 3 --processor cpu --durations 10"
      - execute-command-if-has-matching-changes "$py3_cmd" "test/" "docker/*" "buildspec.yml"
      - py2_cmd="IGNORE_COVERAGE=- tox -e py27 -- test/integration/local --region $AWS_DEFAULT_REGION --docker-base-name $PREPROD_IMAGE --tag $CPU_TAG_PY2 --framework-version $FRAMEWORK_VERSION --py-version 2 --processor cpu --durations 10"
      - execute-command-if-has-matching-changes "$py2_cmd" "test/" "docker/*" "buildspec.yml"

      # run gpu integration tests
      - printf "$SETUP_CMDS" > $SETUP_FILE
      - cmd="IGNORE_COVERAGE=- tox -e py36 -- test/integration/local -n 4 --region $AWS_DEFAULT_REGION --docker-base-name $PREPROD_IMAGE --tag $GPU_TAG_PY3 --framework-version $FRAMEWORK_VERSION --py-version 3 --processor gpu --durations 10"
      - py3_cmd="remote-test --github-repo $GITHUB_REPO --test-cmd \"$cmd\" --setup-file $SETUP_FILE --pr-number \"$PR_NUM\""
      - execute-command-if-has-matching-changes "$py3_cmd" "test/" "docker/*" "buildspec.yml"

      - cmd="IGNORE_COVERAGE=- tox -e py27 -- test/integration/local -n 4 --region $AWS_DEFAULT_REGION --docker-base-name $PREPROD_IMAGE --tag $GPU_TAG_PY2 --framework-version $FRAMEWORK_VERSION --py-version 2 --processor gpu --durations 10"
      - py2_cmd="remote-test --github-repo $GITHUB_REPO --test-cmd \"$cmd\" --setup-file $SETUP_FILE --pr-number \"$PR_NUM\" --skip-setup"
      - execute-command-if-has-matching-changes "$py2_cmd" "test/" "docker/*" "buildspec.yml"

      # run sagemaker tests
      - test_cmd="IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker -n 8 --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --account-id $ACCOUNT --tag $CPU_TAG_PY3 --py-version 3 --processor cpu --durations 10"
      - execute-command-if-has-matching-changes "$test_cmd" "test/" "docker/*" "buildspec.yml"
      - test_cmd="IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker -n 8 --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --account-id $ACCOUNT --tag $GPU_TAG_PY3 --py-version 3 --processor gpu --durations 10"
      - execute-command-if-has-matching-changes "$test_cmd" "test/" "docker/*" "buildspec.yml"
      - test_cmd="IGNORE_COVERAGE=- tox -e py27 -- test/integration/sagemaker -n 8 --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --account-id $ACCOUNT --tag $CPU_TAG_PY2 --py-version 2 --processor cpu --durations 10"
      - execute-command-if-has-matching-changes "$test_cmd" "test/" "docker/*" "buildspec.yml"
      - test_cmd="IGNORE_COVERAGE=- tox -e py27 -- test/integration/sagemaker -n 8 --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --account-id $ACCOUNT --tag $GPU_TAG_PY2 --py-version 2 --processor gpu --durations 10"
      - execute-command-if-has-matching-changes "$test_cmd" "test/" "docker/*" "buildspec.yml"

    finally:
      # shut down remote gpu instance
      - cleanup-gpu-instances
      - cleanup-key-pairs

      # remove ecr image
      - delete_cmd="aws ecr batch-delete-image --repository-name $ECR_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$CPU_TAG_PY2"
      - execute-command-if-has-matching-changes "$delete_cmd" "test/" "docker/*" "buildspec.yml"
      - delete_cmd="aws ecr batch-delete-image --repository-name $ECR_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$GPU_TAG_PY2"
      - execute-command-if-has-matching-changes "$delete_cmd" "test/" "docker/*" "buildspec.yml"
      - delete_cmd="aws ecr batch-delete-image --repository-name $ECR_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$CPU_TAG_PY3"
      - execute-command-if-has-matching-changes "$delete_cmd" "test/" "docker/*" "buildspec.yml"
      - delete_cmd="aws ecr batch-delete-image --repository-name $ECR_REPO --region $AWS_DEFAULT_REGION --image-ids imageTag=$GPU_TAG_PY3"
      - execute-command-if-has-matching-changes "$delete_cmd" "test/" "docker/*" "buildspec.yml"
