ARG region
FROM 763104351884.dkr.ecr.$region.amazonaws.com/tensorflow-training:2.8.0-gpu-py39-cu112-ubuntu20.04

COPY dist/sagemaker_tensorflow_training-*.tar.gz /sagemaker_tensorflow_training.tar.gz
RUN pip install --upgrade --no-cache-dir /sagemaker_tensorflow_training.tar.gz && \
    rm /sagemaker_tensorflow_training.tar.gz
